export function getFormData(form) {
  return Object.fromEntries(new FormData(form)); 
}

// =============================
// FIELD ERROR UPDATE (HELPER)
// =============================
function updateFieldError(form, field, errorMessage) {
  const errorElement = form.querySelector(`#${field.id}-error`);

  if (errorMessage) {
    field.classList.add("invalid");
    field.classList.remove("valid");

    if (errorElement) {
      errorElement.textContent = errorMessage;
      errorElement.classList.add("active");
    }
  } else {
    field.classList.remove("invalid");
    field.classList.add("valid");

    if (errorElement) {
      errorElement.textContent = "";
      errorElement.classList.remove("active");
    }
  }
}

// =============================
// FIELD VALIDATION UI
// =============================
export function validateFieldUI(form, field, errors) {
  updateFieldError(form, field, errors[field.name]); // so in actuall sense we now [opulating the errors object with the field name as key and error message as value]. Remember that the errors object is generated by the validateField function in validation.js and it contains key-value pairs where the key is the field name and the value is the error message (if any). So when we call updateFieldError, we pass in the form, the specific field we want to validate, and the error message associated with that field from the errors object. This way, if there is an error message for that field, it will be displayed; otherwise, it will clear any previous error messages and mark the field as valid.
}

// =============================
// SUBMIT BUTTON STATE
// =============================
export function updateSubmitButtonUI(submitButton, isValid) {
  submitButton.disabled = !isValid; // here we are setting the disabled property of the submit button based on the isValid parameter. If isValid is true, the button will be enabled (disabled = false), and if isValid is false, the button will be disabled (disabled = true). This allows us to control whether the user can submit the form based on the validity of the input fields. isValid is typically determined by the validation logic in the validation.js module, which checks the form data and returns whether it meets the required criteria.
}

// =============================
// MINIMUM DATE CONSTRAINT
// =============================
export function setMinDateUI(dateInput) {
  const now = new Date();
  //Get local year, month, and day
  const year = now.getFullYear();
   const month = String(now.getMonth() + 1).padStart(2, '0'); // Months are 0-indexed
  const day = String(now.getDate()).padStart(2, '0');

   // Combine into YYYY-MM-DD format
  const localToday = `${year}-${month}-${day}`;
  
  dateInput.min = localToday;
 
}

// =============================
// ERROR RENDERING (BATCH)
// =============================
export function renderErrors(form, errors) {
  const fields = form.querySelectorAll("input, select");

  fields.forEach((field) => {
    if (errors[field.name]) {
      field.classList.add("invalid");
      field.classList.remove("valid");

      const errorElement = form.querySelector(`#${field.id}-error`);
      if (errorElement) {
        errorElement.textContent = errors[field.name];
        errorElement.classList.add("active");
      }
    } else {
      field.classList.remove("invalid");
      field.classList.add("valid");

      const errorElement = form.querySelector(`#${field.id}-error`);
      if (errorElement) {
        errorElement.textContent = ""; 
        errorElement.classList.remove("active");
      }
    }
  });
}

// =============================
// CLEAR FIELD STYLES
// =============================
export function clearFieldStyles(fields) {
  fields.forEach((field) => {
    field.classList.remove("valid", "invalid");
  });
}

// =============================
// BUTTON LOADING STATE
// =============================
export function setButtonLoading(submitButton, isLoading) {
  if (isLoading) {
    submitButton.disabled = true;
    submitButton.classList.add("loading");
    const btnText = submitButton.querySelector(".btn-text");
    const btnSpinner = submitButton.querySelector(".btn-spinner");
    if (btnText) btnText.textContent = "Processing...";
    if (btnSpinner) btnSpinner.classList.remove("hidden");
  } else {
    submitButton.classList.remove("loading");
    const btnText = submitButton.querySelector(".btn-text");
    const btnSpinner = submitButton.querySelector(".btn-spinner");
    if (btnText) btnText.textContent = "Book Appointment";
    if (btnSpinner) btnSpinner.classList.add("hidden");
  }
}

// =============================
// TOAST NOTIFICATION
// =============================
export function showToast(message, type = "success") {
  const toast = document.querySelector("#booking-confirmation");
  if (!toast) return;

  toast.textContent = message;
  toast.classList.remove("hidden", "success", "error", "show");
  toast.classList.add(type, "show");

  setTimeout(() => {
    toast.classList.remove("show");
  }, 4000);
}
